### ISSUE TITLE
Inconsistent Function Names in Plugin Version 1.05 (Ghidra 10.3.2)

### ISSUE THREAD

**Issue by KutsuyaYuki** [CreepNT/VitaLoaderRedux#2]
#### Problem
I have encountered an issue related to function names in the latest version of the plugin (`1.05`) when using it with Ghidra version `10.3.2`. It appears that there might be inconsistencies or inaccuracies in the function naming.

#### Expected Behavior
When the plugin is loaded into Ghidra `10.3.2`, and I import the decrypted `eboot.bin.elf`, I expect the functions to have clear and consistent names to maintain code readability and usability.

#### Steps to Reproduce
1. Install Ghidra version `10.3.2`.
2. Load the latest version of the plugin (`1.05`) into Ghidra.
3. Import the decrypted `eboot.bin.elf`.
4. Select the plugin for disassembly.
5. Observe the function names.

#### Actual Behavior
The function names within Ghidra `10.3.2` are not consistent or accurate, causing confusion when working with the plugin and disassembled code.

### Screenshots

| Old Plugin | New Plugin |
|------------|------------|
| ![Old Plugin](https://github.com/CreepNT/VitaLoaderRedux/assets/17732178/6ec6b2a5-4cb6-4733-bd38-320392a1c856) | ![New Plugin](https://github.com/CreepNT/VitaLoaderRedux/assets/17732178/8729d98b-62c5-4a9c-968c-5d12a78467f1) |

**Comment by KutsuyaYuki** [comment]
I fixed it. Here are the steps I followed to resolve the issue:

| Step | Description                                                                                                      |
|------|------------------------------------------------------------------------------------------------------------------|
| 1    | Rerun the analyzer: `Analysis -> Auto Analyze 'eboot.new.elf'`.                                                 |
| 2    | Deselect everything except NID resolution.                                                                      |
| 3    | Select `ExternalDatabase`.                                                                                       |
| 4    | Click `Analyze`.                                                                                                |
| 5    | Choose the correct NID database file.                                                                           |
| 6    | Done.                                                                                                            |

These steps resolved the function name inconsistency problem, and the plugin is now working as expected with Ghidra `10.3.2`.

Here are the images for reference:

![Image 1](https://github.com/CreepNT/VitaLoaderRedux/assets/17732178/70fb7801-470f-4d7e-bb29-8ef0618918a9)

![Image 2](https://github.com/CreepNT/VitaLoaderRedux/assets/17732178/b936d88c-3033-4f2b-bbd5-9a2917dabf70)

**Comment by CreepNT** [comment]
...
![Readme_screenshot.png](https://github.com/CreepNT/VitaLoaderRedux/assets/32939301/c3463918-e2b2-4d2b-ac03-efa16c404d92)

**Comment by KutsuyaYuki** [comment]
Yea, I should stop doing shit at night, sorry for wasting your time!
